Adamfuller zz patch 1
KipCrossing/geotiff pull request #29
Opened 2021-08-30 00:45 UTC by adamfuller-zz

Hi Kip, I wound up closing my original PR and creating this new one.

2021-08-30 02:34 UTC, KipCrossing requested changes

2021-08-30 02:34 UTC, KipCrossing commented on geotiff/geotiff.py
> +            else
@adamfuller-zz Looks like you left out a `:` on your else statement

2021-08-30 02:54 UTC, KipCrossing commented
You can test your changes by running:

```
python -m pytest
```

You may need to install `pytest`

2021-08-30 08:22 UTC, adamfuller-zz commented
God not a great first outing.  Yep I thought I would be clever and make my commit through the github web editor without actually running the code (or using pytest, I'd never used it but I installed it and have run it successfully now yay).  Unfortunately for geotiff, this is the first public repo I have contributed to, your karma is definately +1 now.

2021-08-31 06:22 UTC, KipCrossing approved these changes
Looks good!

2021-08-31 06:25 UTC, KipCrossing commented
> God not a great first outing. Yep I thought I would be clever and make my commit through the github web editor without actually running the code (or using pytest, I'd never used it but I installed it and have run it successfully now yay). Unfortunately for geotiff, this is the first public repo I have contributed to, your karma is definately +1 now.

All good. A great way to learn is to make mistakes - especially in a public setting. I welcome all patches as it's impossible for me to know about all the edge cases; such as this one. Thanks for the PR

2021-08-31 06:25 UTC, merged

2021-08-31 06:29 UTC, KipCrossing commented
The new version it up the your fix: https://pypi.org/project/geotiff/0.2.3/